site_name: Prefect AWS Shared Tasks and Subflow Collection
theme:
  name: material
  palette:
    primary: blue
    accent: blue

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            heading_level: 1
      watch:
        - prefect_aws/
