site_name: prefect-aws
theme:
  name: material
  palette:
    primary: blue
    accent: blue
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - prefect_aws/
<<<<<<< HEAD
        - README.md

nav:
    - Home: index.md
    - Tasks: tasks.md
    - Flows: flows.md

=======

nav:
    - Home: index.md
    - Credentials: credentials.md
    - S3: s3.md
    - Secrets Manager: secrets_manager.md
>>>>>>> ebab90c4ebd9eb4eec21b7ad08c318a8465b5cea
